### ISSUE TITLE
segmentation output potential inconsistencies or fix?

### ISSUE THREAD

**Issue by monajalal** [isl-org/spear#186]
Is there a way to fix the segmentation output so that it shows all pallet objects as a certain color (say green)? Here when there are load on the pallets it shows them pink. 
I prefer to have it such that all pallet objects are green and loads are pink.
![0012](https://user-images.githubusercontent.com/1892917/232535787-d77c03dd-284d-493e-9442-8b2052e1b2fe.png)
![0012](https://user-images.githubusercontent.com/1892917/232535804-c828dd5d-0a49-4021-9eaa-e24793046ae8.png)

Also, are we also output 3D object pose annotations with SpearSim when using generate_images.py?
Further, are we able to only show the segmentation mask/map only for objects of interest (say pallets)?

**Comment by mikeroberts3000** [comment]
**Is there a way to fix the segmentation output so that it shows all pallet objects as a certain color (say green)? Here when there are load on the pallets it shows them pink.**

This is possible, but it will involve some effort. I believe the main issue is that the object you're talking about (a pallet with boxes sitting on top) has already been merged together in the editor into a single asset. There are several possible workarounds. First, you could wait for a future release. It is on our roadmap to group the assets in the warehouse scene more carefully, and also to distribute the raw warehouse scene so it can be edited by end-users. So this issue might go away on its own, or it might be easy for you to edit the object groupings and tags yourself in the editor. Second, you might be able to modify our code for converting semantic tags into stencil values. You may be able to recover the sub-objects somehow using the APIs provided by the Unreal Engine, and then set unique stencil values for them. See [here](https://github.com/isl-org/spear/blob/main/cpp/unreal_plugins/SimulationController/Source/SimulationController/CameraSensor.cpp#L123).

**Are we able to only show the segmentation mask/map only for objects of interest (say pallets)?**

Can't you just ignore all the colors you don't care about in your application? Am I missing something?

**Also, are we also output 3D object pose annotations with SpearSim when using generate_images.py?**

It should be easy to hack our code to return the pose of every object using the C++ APIs provided by the Unreal Engine, e.g., you could return this information in `CameraAgent::getStepInfo()` and it will show up in your Python code when you call `env.step(...)`. However, for this pose information to be useful, you would also need to know what objects you are looking at, i.e., you would need to generate an instance segmentation image. Obtaining such an image would be a bit more complicated, because you couldn't rely directly on using the stencil buffer, which only allows for integer values between 0-255. Instead, you'd need to design a custom post-processing material. Both of these features are on our roadmap, but we haven't implemented them yet. Maybe you can help us with this, since you might need to do it in your application anyway.
