### ISSUE TITLE
Taking photos of only objects of interest not random objects

### ISSUE THREAD

**Issue by monajalal** [isl-org/spear#195]
Is there a way for the generate_poses.py to create random poses for camera with constraint in mind that object of interest should be in the view of camera? Or is this a feature already available? Could you please guide how to use it? We are interested in not random photos but random photos with objects of interest in the view of camera.

**Comment by mikeroberts3000** [comment]
Hi @monajalal, the easiest approach in the current release is probably to generate your own camera poses with your preferred views, save them to a CSV file, and then pass the CSV file into `generate_images.py` in our `generate_image_dataset` example. In order to determine the location of the object(s) of interest, you can do the following: build a `Development` build of SpearSim; open your preferred scene using `run_executable.py`; press the tilde key to bring up the Unreal Engine debug console; type `ToggleDebugCamera`. This will print the current location of the camera to the viewport, so you can navigate around, manually make a note of locations of interest, and use those locations to inform your strategy of generating your own camera poses.
